hw3: ctest.c File Reference
ctest.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "mystring.h"
#include "structure.h"
Functions
int main ()
Variables
const int MAX_CHARS = 20
Function Documentation
main()
int main ()
References copyPersonArray(), genRandomPerson(), genRandomPersonArray(), make_person(), MAX_CHARS, mystrcat(), mystrcpy(), mystrdup(), mystrlen(), mystrncat(), printPerson(), and printPersonArray().
Variable Documentation
MAX_CHARS
const int MAX_CHARS = 20
ctest.c Program to demonstrate character arrays and dynamically-allocated memory.
Author
Sean Arackal, Mike Ciaraldi, Blake Nelson
Referenced by main().