hw3: mystring.h File Reference
mystring.h File Reference
Functions
char * mystrdup (const char *source)
char * mystrndup (const char *source, size_t n)
size_t mystrlen (const char *source)
char * mystrcpy (char *cpy, const char *source)
char * mystrncpy (char *cpy, const char *source, size_t n)
char * mystrcat (char *target, const char *source)
char * mystrncat (char *target, const char *source, size_t n)
Function Documentation
mystrcat()
char* mystrcat (char * target, const char * source)
Concatenates two string to each other
Parameters
target Pointer to first part of the string which is also the final concatenation
source Pointer to the string to be concatenated to the first string
Returns
pointer to the concatenated string
References mystrlen().
Referenced by main().
mystrcpy()
char* mystrcpy (char * cpy, const char * source)
Copies a C-style string
Parameters
cpy Pointer to string that gets copied
source Pointer to new copy of string
Returns
pointer to the new copy of string
Referenced by main(), and mystrdup().
mystrdup()
char* mystrdup (const char * source)
mystring.h
Author
Mike Ciaraldi, Blake Nelson My own versions of some of the C-style string functions
mystring.c
Author
Sean Arackal, Mike Ciaraldi, Blake Nelson Custom versions of some of the C-style string functions Duplicates a C-style string.
Parameters
source Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of source or null if no memory is available
References mystrcpy(), and mystrlen().
Referenced by main().
mystrlen()
size_t mystrlen (const char * source)
Returns the length of a C-style string
Parameters
source Pointer to string of which the length we need to calculate
Returns
integer value of the length of the string
Referenced by genRandomPerson(), main(), make_person(), mystrcat(), mystrdup(), mystrncat(), mystrncpy(), and mystrndup().
mystrncat()
char* mystrncat (char * target, const char * source, size_t n)
Concatenates two string to each other from n chars into source
Parameters
target Pointer to first part of the string which is also the final concatenation
source Pointer to the string to be concatenated to the first string
n the number of characters to concatenate from source to targe
Returns
pointer to the concatenated string
References mystrlen().
Referenced by main().
mystrncpy()
char* mystrncpy (char * cpy, const char * source, size_t n)
Copies the first n bytes of source.
Parameters
cpy Pointer to string that gets copied
source Pointer to new copy of string
n number of bytes
Returns
pointer to the new copy of string
References mystrlen().
Referenced by mystrndup().
mystrndup()
char* mystrndup (const char * source, size_t n)
Duplicates a C-style string up to n characters.
Parameters
source Pointer to string to be duped
n the number of characters to be duped from source
Returns
Pointer to freshly-allocated string containing a duplicate of source or null if no memory is available
References mystrlen(), and mystrncpy().
Referenced by genRandomPerson(), and make_person().