hw3: structure.c File Reference
structure.c File Reference
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include "mystring.h"
#include "structure.h"
Functions
Person * make_person (char *name, int birth_year, int salary)
void printPerson (Person *p)
char genRandomChar ()
char * genRandomString (size_t size)
int genRandomInt (int min, int max)
Person * genRandomPerson ()
Person ** genRandomPersonArray (size_t n)
void printPersonArray (Person **personArray, size_t n)
Person ** copyPersonArray (Person **source, size_t n)
void freePersonArray (Person **personArray, size_t n)
Function Documentation
copyPersonArray()
Person** copyPersonArray (Person ** source, size_t n)
shallow copy an array of persons
Parameters
source The source array.
n A count of the elements in the array.
Returns
pointer to copied array
Referenced by main().
freePersonArray()
void freePersonArray (Person ** personArray, size_t n)
frees an array of persons and frees the pointers
Parameters
personArray the array to free
n tne number of persons
genRandomChar()
char genRandomChar ()
generates a random character
Returns
a random char
Referenced by genRandomString().
genRandomInt()
int genRandomInt (int min, int max)
generates a random integer
Parameters
min for the lowest possible value
max for the max possible value
Returns
a random int
Referenced by genRandomPerson().
genRandomPerson()
Person* genRandomPerson ()
generates a random struct of person type
Returns
a pointer to the random person
References Person::birth_year, genRandomInt(), genRandomString(), mystrlen(), mystrndup(), Person::name, and Person::salary.
Referenced by genRandomPersonArray(), and main().
genRandomPersonArray()
Person** genRandomPersonArray (size_t n)
generates a random array of structs of person type
Parameters
number of random persons
Returns
a pointer to the random array
References genRandomPerson().
Referenced by main().
genRandomString()
char* genRandomString (size_t size)
generates a random string
Parameters
size for the lenght of the random string
Returns
a pointer to the random string
References genRandomChar().
Referenced by genRandomPerson().
make_person()
Person* make_person (char * name, int birth_year, int salary)
structure.c
Author
Sean Arackal class for creating structures creates a persons struct
Parameters
name The name of the person in string
birth_year The birth year of the person
salary The salary of the person in int
Returns
pointer to person struct
References Person::birth_year, mystrlen(), mystrndup(), Person::name, and Person::salary.
Referenced by main().
printPerson()
void printPerson (Person * p)
prints the properties of a person
Parameters
p the person structure
References Person::birth_year, Person::name, and Person::salary.
Referenced by main(), and printPersonArray().
printPersonArray()
void printPersonArray (Person ** personArray, size_t n)
prints a array of structs of person type
Parameters
personArray of random persons
n number of persons
References printPerson().
Referenced by main().